# Generated by Django 4.1 on 2022-08-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracaodeparticipantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('habilidade', models.IntegerField(choices=[(1, 'Excelente(1)'), (2, 'Bom(2)'), (3, 'Intermediário(3)'), (4, 'Em desenvolvimento(4)')])),
            ],
        ),
        migrations.DeleteModel(
            name='CadastrarParticipantes',
        ),
    ]
